const serviceCards = [
    {
        title: 'Client-focused Designs',
        desc: 'Websites designed to attract new clients by showcasing your expertise and building trust.',
        img: '/client-focused.png',
        imgAlt: 'Web designer and client shaking hands, symbolizing trust in client-focused website design.',
    },
    {
        title: 'Strategic content creation',
        desc: 'High-quality content that highlights your services, experience, and client testimonials.',
        img: '/content-creation.png',
        imgAlt: 'Woman brainstorming website content ideas on whiteboard for strategic web development.',
    },
    {
        title: 'Mobile-responsive Designs',
        desc: 'Ensure your website looks great and functions flawlessly on all devices, maximizing client reach.',
        img: '/responsive.png',
        imgAlt: 'Responsive web design displayed across smartphone, tablet, and desktop devices.',
    },
    {
        title: 'Search Engine Optimization (SEO)',
        desc: 'Optimize your website to rank higher in search engine results, increasing organic client discovery.',
        img: '/seo.png',
        imgAlt: 'Web specialist analyzing SEO metrics and search rankings for improved visibility.',
    },
    {
        title: 'Compelling calls to action',
        desc: 'Encourage visitors to contact you with clear and strategic placement of contact forms, phone numbers and booking systems',
        img: '/cta.png',
        imgAlt: 'Web designer showcasing effective call-to-action panel for user engagement.',
    },
    {
        title: 'Social media integration',
        desc: 'Integrate social media platforms seamlessly into your website, allowing visitors to connect with you and share your services on their networks.',
        img: '/socials.png',
        imgAlt: 'Web developer demonstrating social media integration with Facebook, Twitter, and Instagram icons.',
    },
];

const reviews = [
    {
        id: 58,
        title: 'Webex did a great job...',
        desc: 'Webex did a great job building my Shopify website! Easy to use and turned out just how I wanted.',
        img: '/avatar-male.png',
        author: 'Marvin Greene',
        position: 'Restaurant Owner',
        url: 'https://www.trustpilot.com/review/webexis.net',
        date: 'Jan 20, 2024',
        stars: 5,
    },
    {
        id: 402,
        title: 'Did a great job with building my...',
        desc: "Did a great job with building my project, time maintained, quality work, Budget maintained, can, met my expectations really well. Overall, great work , can't complain.Will be working with him again thats definite.",
        img: '/avatar-male.png',
        author: 'Shadman Shad',
        position: 'Healthcare Professional',
        url: 'https://www.trustpilot.com/review/webexis.net',
        date: 'Oct 15, 2023',
        stars: 4,
    },
    {
        id: 19,
        title: 'Made My Restaurant Website Shine',
        desc: "Webexis designed a stunning website for our restaurant that showcases our food and made it easy for customers to order. But it wasn't just looks - their marketing magic brought in new customers. Great communication, industry knowledge, and measurable results - highly recommend!",
        img: '/avatar-male.png',
        author: 'Maikel Ab',
        position: 'Restaurant Owner',
        url: 'https://www.trustpilot.com/review/webexis.net',
        date: 'June 28, 2024',
        stars: 5,
    },
    {
        id: 30,
        title: 'Solid Choice for Dropshipping Stores',
        desc: "Webexis did a good job building my dropshipping website. It's definitely improved my workflow and made managing products easier. While everything looks good, it could've been a little better. Overall, a solid choice, but with room for improvement.",
        img: '/avatar-male.png',
        author: 'Arman Fahim',
        position: 'Dropship Specialist',
        url: 'https://trstp.lt/mmvIrmL-N',
        date: 'Dec 01, 2023',
        stars: 4,
    },
    {
        id: 40,
        title: 'Web Management Bliss: Thanks to WebExis',
        desc: "Managing a website shouldn't feel like rocket science. Webexis gets it. They built me a personal website that's a joy to manage. It's streamlined and user-friendly, making updates and content creation a breeze.  Highly recommend them!",
        img: '/avatar-male.png',
        author: 'Shahed Ahmed',
        position: 'Digital Marketer',
        url: 'https://www.trustpilot.com/review/webexis.net',
        date: 'Oct 15, 2023',
        stars: 5,
    },
];

export { serviceCards, reviews };
