const projects = [
    {
        id: 1,
        title: 'mosaic',
        body: "Leveraging Vite's lightning-fast build and Sass for maintainable styles, we crafted a sleek landing page showcasing Mosaic's drag-and-drop functionality. HTML and JavaScript provided the foundation for interactivity, while Sass ensured a cohesive design across the page.",
        tags: ['social media marketing', 'ads marketing'],
        img: '/tset1.png',
        liveUrl: 'https://mosaic-wp.netlify.app/',
        githubUrl: 'view-source:https://mosaic-wp.netlify.app/',
    },
    {
        id: 2,
        title: 'easyielts',
        body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestias dolore ea pariatur repellendus? Modi reiciendis, ipsam asperiores labore error, quas odit molestias et, quod fugiat mollitia placeat architecto? Vero.',
        tags: ['social media marketing', 'ads marketing'],
        img: '/tset2.png',
        liveUrl: 'https://mosaic-wp.netlify.app/',
        githubUrl: '',
    },
    {
        id: 3,
        title: 'shahedexpo',
        body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestias dolore ea pariatur repellendus? Modi reiciendis, ipsam asperiores labore error, quas odit molestias et, quod fugiat mollitia placeat architecto? Vero.',
        tags: ['web develpment', 'ads marketing'],
        img: '/tset3.png',
        liveUrl: 'https://mosaic-wp.netlify.app/',
        githubUrl: '',
    },
    {
        id: 4,
        title: 'webexis',
        body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestias dolore ea pariatur repellendus? Modi reiciendis, ipsam asperiores labore error, quas odit molestias et, quod fugiat mollitia placeat architecto? Vero.',
        tags: ['web design', 'web developemt'],
        img: '/tset4.png',
        liveUrl: 'https://mosaic-wp.netlify.app/',
        githubUrl: '',
    },
    {
        id: 5,
        title: 'easyielts',
        body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestias dolore ea pariatur repellendus? Modi reiciendis, ipsam asperiores labore error, quas odit molestias et, quod fugiat mollitia placeat architecto? Vero.',
        tags: ['social media marketing', 'ads marketing'],
        img: '/test-project.jpg',
        liveUrl: 'https://mosaic-wp.netlify.app/',
        githubUrl: '',
    },
    {
        id: 6,
        title: 'shahedexpo',
        body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestias dolore ea pariatur repellendus? Modi reiciendis, ipsam asperiores labore error, quas odit molestias et, quod fugiat mollitia placeat architecto? Vero.',
        tags: ['web develpment', 'ads marketing'],
        img: '/test-project.jpg',
        liveUrl: 'https://mosaic-wp.netlify.app/',
        githubUrl: '',
    },
];
export default projects;
